### ISSUE TITLE
Scan does not work for macOS High Sierra

### ISSUE THREAD

**Issue by mihui** [hybridgroup/cylon-ble#20]
There is no logs when the scan is being executed.

**Comment by aurman** [comment]
I've managed to get the scanning working by pulling down an experimental branch of noble. More detail here: https://github.com/sandeepmistry/noble/issues/679

Relevant part:

You can have npm install from my git branch with
`npm install git://github.com/jacobrosenthal/noble.git#highsierra` or edit your package.json and add the branch to your dependencies

```
  "dependencies": {
    "noble": "git://github.com/jacobrosenthal/noble.git#highsierra"
  }
```

**Comment by mihui** [comment]
Thanks @aurman , it's really helpful.
